document.writeln('<div class="softdown">');
document.writeln('<div class="softdown_t"><h2>软件专区</h2>');
document.writeln('<ul>');
document.writeln('<li><a href="http://www.onlinedown.net/special_1424.htm">腾讯QQ</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/special_9471.htm">MSN</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/special_21754.htm">迅雷</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/special_108530.htm">IE9</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/special_3123.htm">傲游</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/special_23764.htm">酷狗</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/special_51436.htm">光影</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/special_74160.htm">美图</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/special_49946.htm">搜狗</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/special_50671.htm">360</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/special_15949.htm">瑞星</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/special_25918.htm">暴风</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/special_96645.htm">WPS</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/special_36437.htm">Foxit</a></li>');
document.writeln('</ul></div>');
document.writeln('<div class="hdm07"> <h3><a href="#" target="_blank" style="margin-left:10px;">热门软件</a><a href="#" target="_blank" class="midd">即时通讯</a><a href="#" target="_blank">下载工具</a></a><a href="#" target="_blank">网络电视</a></a><a href="#" target="_blank">安全防护</a></a><a href="#" target="_blank">汉字输入</a></a><a href="#" target="_blank">主页浏览</a></a><a href="#" target="_blank">影音播放</a><a href="#" target="_blank">图文处理</a></h3>');
document.writeln('<div class="content">');
document.writeln('<ul>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">流行：</li>');
document.writeln('<li><a href="http://www.newhua.com/adimg/src-newhua_hao123inst.zip" style=\"color:#c00;\">hao123桌面版</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/21589.htm">财猫浏览器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/49946.htm">搜狗拼音</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/115739.htm">全能播放器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/7677.htm">极品五笔</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/50671.htm">360安全卫士</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">最新：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/111883.htm">华军下载器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/898.htm">风行电影</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/39907.htm">PPTV网络电视</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/115744.htm">奇艺影音</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/25918.htm">暴风影音</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/116871.htm">快播播放软件</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('</ul>');
document.writeln('<ol class="microblog">');
document.writeln('<h2><a href="http://weibo.com/newhuawang"><img src="http://pic.newhua.com/newindex/images/newhua.jpg" width="50" height="50" /></a></h2>');
document.writeln('<h4><a href="http://weibo.com/newhuawang">牛华网</a></h4>');
document.writeln('<h5><a href="http://weibo.com/newhuawang">+关注</a></h5>');
document.writeln('<p>牛华网新浪官方微博</p>');
document.writeln('</ol></div>');
document.writeln('<div class="content" style="display:none;">');
document.writeln('<ul>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">流行：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/1424.htm">腾讯QQ</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/50032.htm">阿里旺旺</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/179.htm">新浪UC</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/35938.htm">微软Skype</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/53887.htm">中移动飞信</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/9471.htm">微软MSN</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">最新：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/41928.htm">谷歌Talk</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/74678.htm">YY语音</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/61421.htm">清扬即时通信</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/91610.htm">人人桌面</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/86154.htm">天翼Live</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/96502.htm">网易CC</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('</ul>');
document.writeln('<ol class="microblog">');
document.writeln('<h2><a href="http://weibo.com/newhuawang"><img src="http://pic.newhua.com/newindex/images/newhua.jpg" width="50" height="50" /></a></h2>');
document.writeln('<h4><a href="http://weibo.com/newhuawang">牛华网</a></h4>');
document.writeln('<h5><a href="http://weibo.com/newhuawang">+关注</a></h5>');
document.writeln('<p>牛华网新浪官方微博</p>');
document.writeln('</ol></div>');
document.writeln('<div class="content" style="display:none;">');
document.writeln('<ul>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">流行：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/21754.htm">迅雷7</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/53593.htm">腾讯QQ旋风</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/26970.htm">比特精灵</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/35264.htm">优酷下载器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/57664.htm">网际快车</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/26970.htm">比特精灵</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">最新：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/114962.htm">优蛋</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/108496.htm">豆丁文档下载器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/19165.htm">BitTorrent</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/105146.htm">盛大下载器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/28718.htm">飞鸟简体版</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/92485.htm">米人</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('</ul>');
document.writeln('<ol class="microblog">');
document.writeln('<h2><a href="http://weibo.com/newhuawang"><img src="http://pic.newhua.com/newindex/images/newhua.jpg" width="50" height="50" /></a></h2>');
document.writeln('<h4><a href="http://weibo.com/newhuawang">牛华网</a></h4>');
document.writeln('<h5><a href="http://weibo.com/newhuawang">+关注</a></h5>');
document.writeln('<p>牛华网新浪官方微博</p>');
document.writeln('</ol></div>');
document.writeln('<div class="content" style="display:none;">');
document.writeln('<ul>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">流行：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/39907.htm">PPTV网络电视</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/898.htm">风行电影</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/79088.htm">迅雷看看</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/40670.htm">PPS网络电视</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/44708.htm">UUsee网络电视</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/112771.htm">百度影音</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">最新：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/115744.htm">奇艺影音</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/61589.htm">久久影音</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/17617.htm">搜迅播放器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/93007.htm">沸点网络电视</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/69766.htm">Cbox</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/41565.htm">蚂蚁网络电视</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('</ul>');
document.writeln('<ol class="microblog">');
document.writeln('<h2><a href="http://weibo.com/newhuawang"><img src="http://pic.newhua.com/newindex/images/newhua.jpg" width="50" height="50" /></a></h2>');
document.writeln('<h4><a href="http://weibo.com/newhuawang">牛华网</a></h4>');
document.writeln('<h5><a href="http://weibo.com/newhuawang">+关注</a></h5>');
document.writeln('<p>牛华网新浪官方微博</p>');
document.writeln('</ol></div>');
document.writeln('<div class="content" style="display:none;">');
document.writeln('<ul>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">安全：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/50671.htm">360安全卫士</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/special_15949.htm">瑞星杀毒软件</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/17120.htm">金山毒霸</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/18353.htm">卡巴斯基</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/101570.htm">小红伞免费版</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/65833.htm">金山卫士</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">辅助：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/72419.htm">驱动人生</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/3450.htm">驱动精灵</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/76322.htm">鲁大师</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/2636.htm">超级兔子</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/32855.htm">一键还原</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/4832.htm">按键精灵</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('</ul>');
document.writeln('<ol class="microblog">');
document.writeln('<h2><a href="http://weibo.com/newhuawang"><img src="http://pic.newhua.com/newindex/images/newhua.jpg" width="50" height="50" /></a></h2>');
document.writeln('<h4><a href="http://weibo.com/newhuawang">牛华网</a></h4>');
document.writeln('<h5><a href="http://weibo.com/newhuawang">+关注</a></h5>');
document.writeln('<p>牛华网新浪官方微博</p>');
document.writeln('</ol></div>');
document.writeln('<div class="content" style="display:none;">');
document.writeln('<ul>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">拼音：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/49946.htm">搜狗拼音</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/56938.htm">谷歌拼音</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/95792.htm">百度PC输入法</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/57099.htm">全拼输入法</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/28270.htm">微软拼音输入法</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/10440.htm">拼音加加</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">五笔：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/7677.htm">极品五笔</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/45267.htm">搜狗五笔</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/24850.htm">极点五笔</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/106347.htm">数字五笔</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/1165.htm">万能五笔</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/4648.htm">念青五笔</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('</ul>');
document.writeln('<ol class="microblog">');
document.writeln('<h2><a href="http://weibo.com/newhuawang"><img src="http://pic.newhua.com/newindex/images/newhua.jpg" width="50" height="50" /></a></h2>');
document.writeln('<h4><a href="http://weibo.com/newhuawang">牛华网</a></h4>');
document.writeln('<h5><a href="http://weibo.com/newhuawang">+关注</a></h5>');
document.writeln('<p>牛华网新浪官方微博</p>');
document.writeln('</ol></div>');
document.writeln('<div class="content" style="display:none;">');
document.writeln('<ul>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">国际：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/108530.htm">IE9浏览器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/7993.htm">chrome浏览器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/108022.htm">Avant浏览器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/2702.htm">Opera</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/59990.htm">safari</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/9819.htm">火狐浏览器</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">国内：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/92127.htm">糖果浏览器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/62857.htm">瑞星安全浏览器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/78249.htm">搜狗浏览器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/3123.htm">傲游浏览器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/45258.htm">360安全浏览器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/105557.htm">QQ浏览器</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('</ul>');
document.writeln('<ol class="microblog">');
document.writeln('<h2><a href="http://weibo.com/newhuawang"><img src="http://pic.newhua.com/newindex/images/newhua.jpg" width="50" height="50" /></a></h2>');
document.writeln('<h4><a href="http://weibo.com/newhuawang">牛华网</a></h4>');
document.writeln('<h5><a href="http://weibo.com/newhuawang">+关注</a></h5>');
document.writeln('<p>牛华网新浪官方微博</p>');
document.writeln('</ol></div>');
document.writeln('<div class="content" style="display:none;">');
document.writeln('<ul>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">视频：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/25918.htm">暴风影音</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/4650.htm">快播播放器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/40766.htm">皮皮播放器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/79088.htm">迅雷看看</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/4727.htm">QuickTime</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/72669.htm">QQ影音</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">音乐：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/8350.htm">千千静听</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/3116.htm">QQ音乐</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/44034.htm">酷我音乐</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/89639.htm">酷狗音乐</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/52639.htm">MvBox音乐</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/107280.htm">多米音乐</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('</ul>');
document.writeln('<ol class="microblog">');
document.writeln('<h2><a href="http://weibo.com/newhuawang"><img src="http://pic.newhua.com/newindex/images/newhua.jpg" width="50" height="50" /></a></h2>');
document.writeln('<h4><a href="http://weibo.com/newhuawang">牛华网</a></h4>');
document.writeln('<h5><a href="http://weibo.com/newhuawang">+关注</a></h5>');
document.writeln('<p>牛华网新浪官方微博</p>');
document.writeln('</ol></div>');
document.writeln('<div class="content" style="display:none;">');
document.writeln('<ul>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">处理：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/24247.htm">Photoshop</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/26604.htm">CorelDRAW</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/51436.htm">光影魔术手</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/74160.htm">美图秀秀</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/76941.htm">可牛影像</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/39528.htm">iSee图片专家</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('<li style="text-align:left; font-weight:bold; width:50px;">浏览：</li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/23183.htm">ACDSee</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/79408.htm">美图看看</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/68625.htm">POCO图片浏览器</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/1389.htm">XnView</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/92509.htm">可牛看图</a></li>');
document.writeln('<li><a href="http://www.onlinedown.net/soft/35790.htm">黄金眼</a></li>');
document.writeln('<li style="width:50px; text-align:right;"><a href="#">更多>></a></li>');
document.writeln('</ul>');
document.writeln('<ol class="microblog">');
document.writeln('<h2><a href="http://weibo.com/newhuawang"><img src="http://pic.newhua.com/newindex/images/newhua.jpg" width="50" height="50" /></a></h2>');
document.writeln('<h4><a href="http://weibo.com/newhuawang">牛华网</a></h4>');
document.writeln('<h5><a href="http://weibo.com/newhuawang">+关注</a></h5>');
document.writeln('<p>牛华网新浪官方微博</p>');
document.writeln('</ol></div>');
document.writeln('</div></div>');