document.writeln("<div class=\"topic\">");
document.writeln("  <div class=\"l_t\"><h2><a href=\"#\">专题策划<\/a><\/h2><h3><img src=\"http:\/\/pic.newhua.com\/newindex\/images\/ms.gif\" width=\"100\" height=\"25\" \/><\/h3>");
document.writeln("  <\/div>");
document.writeln("  <div class=\"box\">");
document.writeln("  <ul>");
document.writeln("  <h2><a href=\"http://news.newhua.com/zt/2011/vote/\" class=\"focusimg\"><img src=\"http:\/\/pic.newhua.com\/newindex\/images\/ms1.jpg\" width=\"120\" height=\"90\" \/><\/a><\/h2>");
document.writeln("  <h3><a href=\"http://news.newhua.com/zt/2011/vote/\">2011华军软件园软件评选<\/a><\/h3>");
document.writeln("  <p> 随着年终的来临，第四届华军软件园我最喜爱的软件评选正式启动。<\/p>");
document.writeln("  <\/ul>");
document.writeln("  <ol>");
document.writeln("  <li><a href=\"http://news.newhua.com/zt/2011/qqt/\">QQ通讯录全新升级<\/a><\/li>");
document.writeln("  <li><a href=\"http://news.newhua.com/zt/2011/dudubao/\">读览天下：移动阅读利器<\/a><\/li>");
document.writeln("  <li><a href=\"http://news.newhua.com/zt/2011/sunlogin/\">向日葵远控软件永久免费<\/a><\/li>");
document.writeln("  <li><a href=\"http://news.newhua.com/zt/2011/zwcad/\">中望CAD2012正式版发布<\/a><\/li>");
document.writeln("  <li><a href=\"http://news.newhua.com/zt/2011/meitu06/\">五大秘招教你做新年美图<\/a><\/li>");
document.writeln("  <li><a href=\"http://news.newhua.com/zt/2010/netpas/\">终极网络加速NETPAS<\/a><\/li>");
document.writeln("  <li><a href=\"http://news.newhua.com/zt/2011/ths01/\">同花顺绿色通道专版<\/a><\/li>");
document.writeln("  <li><a href=\"http://news.newhua.com/zt/2011/avg2012/\">AVG2012免费版发布<\/a><\/li>");
document.writeln("  <\/ol>");
document.writeln("  <\/div>");
document.writeln("<\/div>");