<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/25 0025
 * Time: 上午 9:34
 */

namespace app\article\controller;


use think\Controller;

class Common extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $titleConf = db('conf')->where(['cnname'=>'新闻板块站点名称'])->value('value');
        $this->assign('titleConf',$titleConf);
        if(isset($_COOKIE['session_id'])){
            session_id($_COOKIE['session_id']);
            session('n','');
            if(isset($_SESSION['user_id'])){
                session('user_id',$_SESSION['user_id']);
            }
            if(isset($_SESSION['username'])){
                session('username',$_SESSION['username']);
            }
            if(isset($_SESSION['userpic'])){
                session('userpic',$_SESSION['userpic']);
            }
        }
    }
}